// regex.idl : IDL source for regex.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (regex.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(95FA40E4-577E-47A6-BAF4-7D5529E20AE3),
	version(1.0),
	helpstring("regex 1.0 Type Library")
]
library REGEXLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

};
